import TABS from "./tabs";
import {
  VIDEO_PLAYER_HEIGHT,
  VIDEO_PLAYER_WIDTH,
  RESOLUTIONS,
  ASPECT_RATIO,
  RESOLVED_VIDEO_WIDTH,
} from "./videoDimensions";

export {
  TABS,
  VIDEO_PLAYER_HEIGHT,
  VIDEO_PLAYER_WIDTH,
  RESOLUTIONS,
  ASPECT_RATIO,
  RESOLVED_VIDEO_WIDTH,
};
